# Netlify 部署配置
# 專案: 客戶資料管理系統
# 版本: v1.0

[build]
  # 發布目錄(靜態網站根目錄)
  publish = "."
  
  # 無需建置指令(純前端專案)
  command = ""

# 重定向規則 - SPA 路由支援
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # 排除實際存在的檔案
  conditions = {path = "!*.html"}

# 自訂 HTTP Headers
[[headers]]
  for = "/*"
  [headers.values]
    # 安全性 Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache 控制
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 404 錯誤處理
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404